const { Resend } = require('resend');

const resend = new Resend(process.env.RESEND_API_KEY);

const sendAlibiReport = async (to, verdict, timeline) => {
  try {
    const subject = `Digital Alibi Verifier Report - ${verdict.result === 'TRUE' ? 'Alibi Supported' : 'Alibi Invalidated'}`;

    const html = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h1 style="color: #333; text-align: center;">Digital Alibi Verifier Report</h1>

        <div style="background-color: ${verdict.result === 'TRUE' ? '#d4edda' : '#f8d7da'}; padding: 20px; border-radius: 5px; margin: 20px 0;">
          <h2 style="color: ${verdict.result === 'TRUE' ? '#155724' : '#721c24'}; margin-top: 0;">
            Verdict: ${verdict.result === 'TRUE' ? 'ALIBI SUPPORTED' : 'ALIBI INVALIDATED'}
          </h2>
          <p style="margin-bottom: 0; color: ${verdict.result === 'TRUE' ? '#155724' : '#721c24'};">
            ${verdict.reason}
          </p>
        </div>

        <h3>Timeline Summary</h3>
        <div style="background-color: #f8f9fa; padding: 15px; border-radius: 5px;">
          ${timeline.length > 0
            ? timeline.map(event => `
                <div style="margin-bottom: 10px; padding: 10px; background-color: white; border-radius: 3px;">
                  <strong>${new Date(event.timestamp).toLocaleString()}</strong><br>
                  ${event.type}: ${event.details}
                </div>
              `).join('')
            : '<p>No activity detected during the claimed time period.</p>'
          }
        </div>

        <div style="margin-top: 30px; padding: 20px; background-color: #e9ecef; border-radius: 5px;">
          <p style="margin: 0; font-size: 12px; color: #6c757d;">
            This report was generated by Digital Alibi Verifier. All data analysis is based on user-consented digital activity logs.
          </p>
        </div>
      </div>
    `;

    const data = await resend.emails.send({
      from: 'Digital Alibi Verifier <noreply@digitalalibiverifier.com>',
      to: [to],
      subject: subject,
      html: html,
    });

    console.log('Email sent successfully:', data);
    return data;
  } catch (error) {
    console.error('Error sending email:', error);
    throw new Error('Failed to send email report');
  }
};

module.exports = { sendAlibiReport };
